spring.application.name=rps
spring.profiles.active=local
spring.datasource.url=jdbc:postgresql://localhost:5432/rps-db
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
server.port=8080
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.main.allow-circular-references=true
logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG